name: Deploy Output Assets

on:
  workflow_run:
    workflows:
      - GitHub Snake Game
      - GitHub Metrics (Top Languages)
    types: [ completed ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy dist to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update assets [skip ci]"
